// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FindMaxIndex
int FindMaxIndex(arma::vec x, double maxVal);
RcppExport SEXP _Buddle_FindMaxIndex(SEXP xSEXP, SEXP maxValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxVal(maxValSEXP);
    rcpp_result_gen = Rcpp::wrap(FindMaxIndex(x, maxVal));
    return rcpp_result_gen;
END_RCPP
}
// yVec
arma::vec yVec(arma::vec xVec, arma::mat ZList, arma::mat cList, arma::mat ZFinal, arma::vec cFinal, arma::mat W, arma::vec b, int nLayer, int q, int nModel);
RcppExport SEXP _Buddle_yVec(SEXP xVecSEXP, SEXP ZListSEXP, SEXP cListSEXP, SEXP ZFinalSEXP, SEXP cFinalSEXP, SEXP WSEXP, SEXP bSEXP, SEXP nLayerSEXP, SEXP qSEXP, SEXP nModelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xVec(xVecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZList(ZListSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cList(cListSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZFinal(ZFinalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cFinal(cFinalSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nLayer(nLayerSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nModel(nModelSEXP);
    rcpp_result_gen = Rcpp::wrap(yVec(xVec, ZList, cList, ZFinal, cFinal, W, b, nLayer, q, nModel));
    return rcpp_result_gen;
END_RCPP
}
// MainFunc_Mat
List MainFunc_Mat(arma::vec YTest, arma::mat XTest, arma::vec Y_Train, arma::mat X_Train, arma::mat t_Train, int nN, int nBatch, int nMethod, double lr, int nStep, int nLayer, int q, int r, int nModel);
RcppExport SEXP _Buddle_MainFunc_Mat(SEXP YTestSEXP, SEXP XTestSEXP, SEXP Y_TrainSEXP, SEXP X_TrainSEXP, SEXP t_TrainSEXP, SEXP nNSEXP, SEXP nBatchSEXP, SEXP nMethodSEXP, SEXP lrSEXP, SEXP nStepSEXP, SEXP nLayerSEXP, SEXP qSEXP, SEXP rSEXP, SEXP nModelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type YTest(YTestSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XTest(XTestSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y_Train(Y_TrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_Train(X_TrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t_Train(t_TrainSEXP);
    Rcpp::traits::input_parameter< int >::type nN(nNSEXP);
    Rcpp::traits::input_parameter< int >::type nBatch(nBatchSEXP);
    Rcpp::traits::input_parameter< int >::type nMethod(nMethodSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type nStep(nStepSEXP);
    Rcpp::traits::input_parameter< int >::type nLayer(nLayerSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nModel(nModelSEXP);
    rcpp_result_gen = Rcpp::wrap(MainFunc_Mat(YTest, XTest, Y_Train, X_Train, t_Train, nN, nBatch, nMethod, lr, nStep, nLayer, q, r, nModel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Buddle_FindMaxIndex", (DL_FUNC) &_Buddle_FindMaxIndex, 2},
    {"_Buddle_yVec", (DL_FUNC) &_Buddle_yVec, 10},
    {"_Buddle_MainFunc_Mat", (DL_FUNC) &_Buddle_MainFunc_Mat, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_Buddle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
