# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
FindMaxIndex <- function(x, maxVal) {
    .Call('_Buddle_FindMaxIndex', PACKAGE = 'Buddle', x, maxVal)
}

#' @keywords internal
yVec <- function(xVec, ZList, cList, ZFinal, cFinal, W, b, nLayer, q, nModel) {
    .Call('_Buddle_yVec', PACKAGE = 'Buddle', xVec, ZList, cList, ZFinal, cFinal, W, b, nLayer, q, nModel)
}

#' @keywords internal
MainFunc_Mat <- function(YTest, XTest, Y_Train, X_Train, t_Train, nN, nBatch, nMethod, lr, nStep, nLayer, q, r, nModel) {
    .Call('_Buddle_MainFunc_Mat', PACKAGE = 'Buddle', YTest, XTest, Y_Train, X_Train, t_Train, nN, nBatch, nMethod, lr, nStep, nLayer, q, r, nModel)
}

